# Generated by Django 5.1.5 on 2025-01-26 22:38

import django.core.validators
import gob.models.empresa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[gob.models.empresa.Empresa.validar_rfc])),
                ('regimen_fiscal', models.CharField(choices=[('GENERAL', 'General de Ley'), ('SIMPLIFICADO', 'Régimen Simplificado de Confianza'), ('RESIDENTE', 'Residente en el Extranjero')], max_length=12)),
                ('nombre_contacto', models.CharField(help_text='Nombre de la persona de contacto.', max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre de contacto solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('telefono_contacto', models.CharField(help_text='Teléfono de la persona de contacto.', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser un número de 10 dígitos.', regex='^\\d{10}$')])),
                ('razon_social', models.CharField(help_text='Nombre de la empresa o persona física.', max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('direccion_fiscal', models.TextField(help_text='Dirección fiscal de la empresa o persona física.', validators=[django.core.validators.MinLengthValidator(5)])),
                ('codigo_postal', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')])),
                ('certificado', models.FileField(blank=True, null=True, upload_to='empresas/cer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer'])])),
                ('cer_key', models.FileField(blank=True, null=True, upload_to='empresas/key/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['key'])])),
            ],
        ),
    ]
