# Generated by Django 5.1.5 on 2025-01-26 23:36

import django.core.validators
import gob.models.cliente
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gob', '0002_empresa_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13, unique=True, validators=[gob.models.cliente.Cliente.validar_rfc])),
                ('direccion_fiscal', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='La dirección fiscal debe tener al menos 10 caracteres')])),
                ('contacto_principal', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('telefono_contacto', models.CharField(help_text='Teléfono de la persona de contacto.', max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ser un número de 10 dígitos.', regex='^\\d{10}$')])),
                ('forma_pago', models.CharField(max_length=100)),
                ('cuenta_pago', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La cuenta de pago debe tener entre 10 y 18 dígitos.', regex='^\\d{10,18}$')])),
            ],
        ),
    ]
